CREATE DATABASE WORKSHOP;
 USE WORKSHOP;
 
 CREATE TABLE USER_INFORMATION(
	USER_NAME VARCHAR(200) NOT NULL,
    CONTACT_NUMBER INT UNIQUE NOT NULL,
    EMAIL VARCHAR(200) UNIQUE,
    ADDRESS VARCHAR(500) NOT NULL,
    AGE INT NOT NULL CHECK (AGE>18),
    STATE VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(200) DEFAULT 'INDIA',
    AADHAR_NUMBER BIGINT NOT NULL,
    USER_ID INT AUTO_INCREMENT PRIMARY KEY
);
DROP TABLE USER_INFORMATION;
SELECT * FROM USER_INFORMATION;
ALTER TABLE USER_INFORMATION CHANGE CONTACT_NUMBER PHONE_NUMBER BIGINT;

INSERT INTO USER_INFORMATION VALUES("KAVANA",9686114934,"KAVANA@GMAIL.COM","1ST CROSS SRINAGAR",19,"KARNATAKA",'',987545674325,1);
TRUNCATE TABLE USER_INFORMATION;
INSERT INTO USER_INFORMATION(USER_NAME,PHONE_NUMBER,EMAIL,ADDRESS,AGE,STATE,AADHAR_NUMBER)VALUES(
'KAVANA',9845512290,'KAVANA@GMAIL.COM','2ND CROSS SRI NAGAR',19,'MAHARASHTRA',987656784563),
('KAVYA',7869512290,'KAVYA@GMAIL.COM','2ND CROSS SRI NAGAR',23,'KARNATAKA',982376545678),
('KEERTHI',9847812290,'KEERTHI@GMAIL.COM','2ND CROSS SRR NAGAR',22,'KERALA',897653484563),
('KAVERI',7856748290,'KAVERI@GMAIL.COM','2ND CROSS SRI NAGAR',20,'GOA',927896784563),
('KAVANA',8965512290,'KAVANAAR@GMAIL.COM','2ND CROSS SRI NAGAR',23,'KERALA',917657884563);

SELECT * FROM USER_INFORMATION HAVING STATE = "KARNATAKA";

SELECT COUNT(STATE) FROM USER_INFORMATION GROUP BY STATE;

SELECT STATE, COUNT(STATE) FROM USER_INFORMATION GROUP BY STATE;

SELECT STATE, COUNT(STATE) FROM USER_INFORMATION GROUP BY STATE HAVING STATE = "KARNATAKA";

SELECT STATE, COUNT(STATE) FROM USER_INFORMATION GROUP BY STATE HAVING STATE = "KERALA";

SELECT STATE,USER_NAME,COUNT(STATE) FROM USER_INFORMATION GROUP BY STATE HAVING STATE = "KERALA" AND USER_NAME = "KEERTHI";
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

SELECT STATE, USER_NAME, COUNT(STATE) 
FROM USER_INFORMATION 
GROUP BY STATE 
HAVING STATE ="KERALA" AND USER_NAME = "KEERTHI";

