CREATE DATABASE DAY03;

USE DAY03;

CREATE TABLE PRODUCT(
	P_ID INT AUTO_INCREMENT PRIMARY KEY,
    P_NAME VARCHAR(25) NOT NULL,
    P_PRICE DECIMAL(10,2),
    P_RATING VARCHAR(25) NOT NULL,
    P_DESCRIPTION VARCHAR(30)
);

CREATE TABLE CUSTOMER(
	C_ID INT AUTO_INCREMENT PRIMARY KEY,
    C_NAME VARCHAR(25) NOT NULL,
    C_ADDRESS VARCHAR(50) NOT NULL,
    C_PHONE_NUMBER VARCHAR(15) NOT NULL UNIQUE,
    C_EMAIL VARCHAR(50) UNIQUE
);

CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    C_ID INT,
    P_ID INT,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID),
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID)
);
DROP TABLE ORDERS;

INSERT INTO CUSTOMER(C_NAME,C_ADDRESS,C_PHONE_NUMBER,C_EMAIL)VALUES
("KAVANA","1st cross srinagar","8089987867","kavana@gmail.com"),
("KAVYA","2nd cross RR nagar","7897876565","kavya@gmail.com"),
("KEERTHI","3rd cross Rajaji nagar","6786778654","keerthi@gmail.com"),
("ABHISHEK","2nd cross Rajaji nagar","7689778654","abhishek@gmail.com"),
("KARTHIK","4th cross RR nagar","8786778654","karthik@gmail.com"),
("AKSHATHA","5TH cross Sri nagar","9876778654","akshatha@gmail.com"),
("ADHYA","5th cross vivek nagar","6756778654","adhya@gmail.com"),
("ARUN","4th cross Rajaji nagar","9086778654","arun@gmail.com"),
("AKSHAY","5th cross Subhash nagar","9786778654","akshay@gmail.com"),
("ASHOK","6th cross RR nagar","8976778654","ashok@gmail.com");

INSERT INTO CUSTOMER VALUES("HARSHA","2ND CROSS RR NAGAR","9099876543","harsha@gmail.com");

SET SQL_SAFE_UPDATES=0;

INSERT INTO PRODUCT(P_NAME,P_PRICE,P_RATING,P_DESCRIPTION)VALUES
("T-Shirt",350.90,"4","Good"),
("Water_bottle",200.90,"5","Excellent"),
("Dress",1350.90,"3","Good"),
("T-Shirt",450.90,"4","Not bad"),
("Shampoo",650.90,"4","Good"),
("Saree",2350.90,"3","Good"),
("Saree",450.90,"4","Good"),
("Tiffan Box",250.90,"4","Good"),
("T-Shirt",550.90,"4","Good"),
("Bag",850.90,"4","Good");

INSERT INTO ORDERS(ORDER_ID,C_ID,P_ID)VALUES(101,2,3),(102,1,2),(104,3,1),(106,6,7),(200,8,9),(234,7,6);

SELECT * FROM ORDERS;

SELECT * FROM CUSTOMER;

SELECT * FROM PRODUCT;

SELECT * FROM ORDERS AS O, CUSTOMER AS C, PRODUCT AS P WHERE O.ORDER_ID = 102 AND O.C_ID=C.C_ID AND O.P_ID = P.P_ID; 

SELECT * FROM CUSTOMER WHERE C_NAME LIKE "K%";

SELECT * FROM PRODUCT WHERE P_NAME LIKE "T%";

SELECT * FROM ORDERS AS O, CUSTOMER AS C, PRODUCT AS P WHERE O.ORDER_ID = 102 AND O.C_ID=C.C_ID AND O.P_ID = P.P_ID AND C.C_NAME LIKE "K%";
 
SELECT * FROM CUSTOMER WHERE C_NAME LIKE "%I";

SELECT * FROM CUSTOMER WHERE C_NAME LIKE "%R%";

SELECT * FROM CUSTOMER WHERE C_NAME LIKE "__E%";

SELECT * FROM CUSTOMER WHERE C_NAME LIKE "__U_";

SELECT * FROM CUSTOMER WHERE C_NAME LIKE "%_K";

SELECT * FROM CUSTOMER AS C INNER JOIN PRODUCT AS P WHERE C.C_ID = P.P_ID;

SELECT * FROM CUSTOMER AS C JOIN PRODUCT AS P WHERE C.C_ID = P.P_ID;

SELECT * FROM PRODUCT AS P JOIN CUSTOMER AS C ON P.P_ID = C.C_ID WHERE C.C_NAME LIKE "K%";

SELECT * FROM CUSTOMER AS C LEFT JOIN PRODUCT AS P ON C.C_ID = P.P_ID;

SELECT * FROM CUSTOMER AS C RIGHT JOIN PRODUCT AS P ON C.C_ID = P.P_ID;

SELECT * FROM CUSTOMER AS C  JOIN PRODUCT AS P ON C.C_ID = P.P_ID;

SELECT * FROM CUSTOMER AS C JOIN PRODUCT AS P ON C.C_NAME = P.P_NAME;

SELECT * FROM CUSTOMER AS C JOIN PRODUCT AS P ON C.C_EMAIL = P.P_RATING;


-- FULL OUTER JOIN 


SELECT * FROM CUSTOMER AS C
LEFT JOIN PRODUCT AS P ON C.C_ID = P.P_ID
UNION 
SELECT * FROM CUSTOMER AS C
RIGHT JOIN PRODUCT AS P ON C.C_ID = P.P_ID
WHERE C.C_ID IS NULL;

SELECT * FROM CUSTOMER UNION SELECT * FROM PRODUCT;

-- SELECT * FROM CUSTOMER AS C FULL OUTER JOIN PRODUCT AS P ON C.C_ID = P.P_ID; 

-- PAGINATION 

SELECT * FROM PRODUCT LIMIT 5;

SELECT * FROM PRODUCT LIMIT 5 OFFSET 2;

SELECT * FROM PRODUCT LIMIT 2 OFFSET 2;

-- SELECT * ORDER WHERE ORDER_ID AND CUSTOMER AS C, PRODUCT AS P WHERE C.C_NAME NOT LIKE "P%"
-- AND C.C_EMAIL = "keerthi@gmail.com" AND P.P_PRICE > AVG(PRICE) GROUP BY ORDER_ID;

-- SELECT PRODUCT_ID, SUM(QUANTITY * TOTAL_PRICE) AS TOTAL_REVENUE FROM ORDERS GROUP BY PRODUCT_ID;

SELECT * FROM PRODUCT AS P WHERE P.P_ID = (SELECT P_ID FROM PRODUCT AS P WHERE P.P_ID = 2); 

-- SELECT AVG(P_PRICE) AS AVERAGE_PRICE FROM PRODUCT;

-- SELECT AVG(P_PRICE) FROM PRODUCT;

SELECT * FROM PRODUCT AS P WHERE P.P_ID = (SELECT AVG(P.P_PRICE) FROM PRODUCT AS P); 

SELECT AVG(P_PRICE) AS AVERAGE_PRICE FROM PRODUCT;

SELECT * FROM PRODUCT AS P WHERE P.P_PRICE >=  (SELECT AVG(P.P_PRICE) FROM PRODUCT AS P); 

SELECT  * FROM ORDERS AS O, PRODUCT AS P WHERE O.P_ID = (SELECT P_ID FROM PRODUCT AS P WHERE P.P_ID = 3);

SELECT  * FROM ORDERS AS O, PRODUCT AS P WHERE P.P_ID = (SELECT P_ID FROM PRODUCT AS P WHERE P.P_ID = 3);

-- SELECT  * FROM ORDERS AS O, PRODUCT AS P WHERE P.P_ID  ALL (SELECT P_ID FROM PRODUCT AS P WHERE P.P_ID = 3);

SELECT  * FROM ORDERS AS O, PRODUCT AS P WHERE P.P_ID = ALL (SELECT P_ID FROM PRODUCT AS P WHERE P.P_ID = 3);

SELECT  * FROM ORDERS AS O, PRODUCT AS P WHERE P.P_ID  != ANY (SELECT P_ID FROM PRODUCT AS P WHERE P.P_ID = 3);

SELECT  * FROM ORDERS AS O, PRODUCT AS P WHERE P.P_ID > ANY (SELECT P_ID FROM PRODUCT AS P WHERE P.P_ID = 3);

SELECT  * FROM ORDERS AS O, PRODUCT AS P WHERE P.P_ID = EXISTS (SELECT P_ID FROM PRODUCT AS P WHERE P.P_ID = 3);

SELECT P_PRICE FROM PRODUCT AS P WHERE NOT EXISTS (SELECT P_PRICE FROM PRODUCT AS P WHERE P.P_PRICE > 500);

SELECT P_PRICE FROM PRODUCT AS P WHERE EXISTS (SELECT P_PRICE FROM PRODUCT AS P WHERE P.P_PRICE > 500);

SELECT ASCII(C_NAME) FROM CUSTOMER;

SELECT LOWER(C_NAME) FROM CUSTOMER;

SELECT SUBSTRING(C_NAME, 0, 100)AS SUB FROM CUSTOMER;

SELECT REVERSE(C_NAME) FROM CUSTOMER;

SELECT SYSDATE() AS DATE;
SELECT YEAR('2024/09/12')AS YEAR;
SELECT MONTH('2024/09/12')AS MONTH;
SELECT MONTHNAME('2024/09/12')AS MONTHNAME;
SELECT DAYNAME('2024/10/26')AS DAYNAME;
SELECT DAY('2024/09/12')AS DAY;

CREATE VIEW VIEW_CUSTOMER AS SELECT C_NAME, C_PHONE_NUMBER FROM CUSTOMER;

SELECT * FROM VIEW_CUSTOMER;

INSERT INTO VIEW_CUSTOMER VALUES("HARSHA",9098998765);


UPDATE VIEW_CUSTOMER SET C_NAME = "Kaveri" where C_PHONE_NUMBER = 7897876565;

INSERT INTO CUSTOMER(C_NAME,C_ADDRESS,C_PHONE_NUMBER,C_EMAIL) VALUES("HARSHA","2ND CROSS RR NAGAR","9099876543","harsha@gmail.com");

SELECT * FROM VIEW_CUSTOMER WHERE C_NAME LIKE "%k%";

DROP VIEW VIEW_CUSTOMER;
