CREATE DATABASE WORKSHOP_DAY_2;

USE WORKSHOP_DAY_2;

CREATE TABLE APPLICATION_DETAILS(
	APP_ID INT AUTO_INCREMENT PRIMARY KEY,
    APP_NAME VARCHAR(200) NOT NULL UNIQUE,
    APP_VERSION VARCHAR(10) NOT NULL,
    NUMBER_OF_USERS INT DEFAULT 0
);

CREATE TABLE USER_DETAILS(
	USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(200) NOT NULL,
    USER_EMAIL VARCHAR(250) NOT NULL UNIQUE,
    APP_ID INT,
	FOREIGN KEY (APP_ID) REFERENCES APPLICATION_DETAILS(APP_ID) ON DELETE SET NULL
);


INSERT INTO APPLICATION_DETAILS(APP_NAME,APP_VERSION,NUMBER_OF_USERS)VALUES("WHATSAPP","2.0V",9),("HOTSTAR","2,9V",4),("FACEBOOK","3.0V",3),("SNAPCHAT","0.4V",4),("TELEGRAM","2.5V",6);

SELECT * FROM APPLICATION_DETAILS;

INSERT INTO USER_DETAILS(USER_NAME,USER_EMAIL,APP_ID)VALUES("ARUN","ARUN03@GMAIL.COM",3),("ASHIK","ASHIK@GMAIL.COM",2);

SELECT * FROM USER_DETAILS;

SELECT * FROM USER_DETAILS AS U, APPLICATION_DETAILS AS A WHERE U.USER_NAME = "ASHIK" AND U.APP_ID = A.APP_ID;

SELECT USER_NAME, APP_NAME FROM USER_DETAILS AS U, APPLICATION_DETAILS AS A WHERE U.USER_ID = 3 AND  U.APP_ID = A.APP_ID;

SELECT AVG(USER_ID) FROM USER_DETAILS;

SELECT SUM(NUMBER_OF_USERS) FROM APPLICATION_DETAILS;

SELECT AVG(NUMBER_OF_USERS) FROM APPLICATION_DETAILS;

SELECT MAX(NUMBER_OF_USERS) FROM APPLICATION_DETAILS;

SELECT MIN(NUMBER_OF_USERS) FROM APPLICATION_DETAILS;

SELECT COUNT(*) FROM USER_DETAILS;

SELECT COUNT(*) FROM APPLICATION_DETAILS;