CREATE DATABASE DETAILS;
DROP DATABASE DETAILS;
CREATE SCHEMA DETAILS;
DROP SCHEMA DETAILS;

USE DETAILS;

CREATE TABLE APPLICATION_DETAILS(
	APP_ID INT,
    APP_NAME VARCHAR(100),
    APP_VERSION VARCHAR(100),
    APP_RELEASE_DATE DATE,
    APP_RELEASE_YEAR YEAR,
    NUMBER_OF_USERS INT
);

RENAME TABLE APPLICATION_DETAILS TO APP_NAME;

DROP TABLE APP_NAME;

ALTER TABLE APPLICATION_DETAILS ADD COLUMN SIZE VARCHAR(50);

SELECT * FROM APPLICATION_DETAILS;

INSERT INTO APPLICATION_DETAILS VALUES(12,"INSTAGRAM","V2.0",2000-02-20,2000,40,"49MB");

INSERT INTO APPLICATION_DETAILS VALUES(12,"INSTAGRAM","V2.0","2000-02-20",2000,40,"49MB");

SELECT * FROM APPLICATION_DETAILS;
INSERT INTO APPLICATION_DETAILS VALUES(14,"WHATSAPP","V20.0","2002-02-24",2002,76,"68MB");

UPDATE APPLICATION_DETAILS SET APP_NAME = "INSTAGRAM_LITE";

SET SQL_SAFE_UPDATES=0;


TRUNCATE APPLICATION_DETAILS;

DROP TABLE APPLICATION_DETAILS;

CREATE TABLE APPLICATION_DETAILS(
	APP_ID INT UNIQUE NOT NULL,
	APP_NAME VARCHAR(100) UNIQUE NOT NULL,
    APP_VERSION VARCHAR(20) NOT NULL,
    APP_RELEASE_DATE DATE NOT NULL,
    APP_RELEASE_YEAR YEAR NOT NULL,
    NUMBER_OF_USERS INT,
    APP_SIZE VARCHAR(20) NOT NULL
); 

INSERT INTO APPLICATION_DETAILS VALUES(01,"SNAPCHAT","2.0V","2000-03-30",2000,40,"20MB");
INSERT INTO APPLICATION_DETAILS VALUES(02,"WHATSAPP","2.30V","2003-03-30",2003,46,"28MB");
INSERT INTO APPLICATION_DETAILS VALUES(03,"FACEBOOK","2.0V","2002-03-30",2002,40,"20MB");
INSERT INTO APPLICATION_DETAILS VALUES(04,"CHATBOT","2.0V","2000-03-30",2000,40,"20MB");
INSERT INTO APPLICATION_DETAILS VALUES(05,"INSTAGRAM","2.0V","2000-03-30",2000,40,"20MB");

SELECT * FROM APPLICATION_DETAILS;

SELECT * FROM APPLICATION_DETAILS WHERE APP_NAME = "WHATSAPP";

SELECT * FROM APPLICATION_DETAILS WHERE APP_ID = 01;

SELECT COUNT(*) FROM APPLICATION_DETAILS;

SELECT COUNT(*) AS COUNT FROM APPLICATION_DETAILS;

SELECT SUM(NUMBER_OF_USERS)FROM APPLICATION_DETAILS;

SELECT SUM(NUMBER_OF_USERS) AS TOTAL FROM APPLICATION_DETAILS;

INSERT INTO APPLICATION_DETAILS VALUES(03,"AIRTEL","2.0V","2004-02-20",2004,48,"29MB");
INSERT INTO APPLICATION_DETAILS VALUES(10,"2.0V","2004-02-20",2004,48,"29MB");
INSERT INTO APPLICATION_DETAILS VALUES(09,"","2.0V","2004-02-20",2004,48,"29MB");

SELECT * FROM APPLICATION_DETAILS WHERE APP_ID >3;

SELECT * FROM APPLICATION_DETAILS WHERE APP_ID < 3;

SELECT * FROM APPLICATION_DETAILS WHERE APP_ID <= 3;

SELECT * FROM APPLICATION_DETAILS WHERE APP_ID >= 3;

SELECT * FROM APPLICATION_DETAILS WHERE APP_ID != 3;

SELECT * FROM APPLICATION_DETAILS WHERE APP_SIZE > "29MB" OR APP_ID = 4;

SELECT * FROM APPLICATION_DETAILS;

SELECT * FROM APPLICATION_DETAILS WHERE APP_SIZE > "20MB" OR APP_ID = 4;

SELECT * FROM APPLICATION_DETAILS WHERE APP_SIZE = "28MB" AND APP_ID = 2;

SELECT * FROM APPLICATION_DETAILS WHERE APP_NAME = "WHATSAPP" AND APP_ID = 4;

SELECT * FROM APPLICATION_DETAILS WHERE APP_NAME = "INSTAGRAM" AND APP_SIZE = "20MB";

SELECT * FROM APPLICATION_DETAILS WHERE APP_NAME != "INSTAGRAM";

SELECT * FROM APPLICATION_DETAILS WHERE APP_NAME = "INSTAGRAM" AND APP_SIZE = "29MB";


