CREATE DATABASE ANOTHER_ONE;

USE ANOTHER_ONE;

CREATE TABLE PANCARD_DETAILS(
	PAN_NUMBER VARCHAR(30) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(25) NOT NULL,
    FATHER_NAME VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(40) NOT NULL,
    AGE INT NOT NULL,
    DOB DATE NOT NULL,
    CITY VARCHAR(20) NOT NULL
);

ALTER TABLE PANCARD_DETAILS ADD COLUMN STATE VARCHAR(20) NOT NULL;

RENAME TABLE PANCARD_DETAILS TO PANCARD;

INSERT INTO PANCARD VALUES("ABC340D4","ADHYA","RAHUL","2ND CROSS RR NAGAR",20,"2002-01-06","BANGLORE","KARNATAKA");
INSERT INTO PANCARD VALUES("KYZ245S8","ARADHANA","RAHUL","1ST CROSS RAJAJI NAGAR",23,"2000-10-26","BANGLORE","KARNATAKA");
INSERT INTO PANCARD VALUES("AYZ078C9","ASHIK","RAJESH","2ND CROSS NEHRU NAGAR",21,"2003-05-06","SHIVAMOGGA","KARNATAKA");
INSERT INTO PANCARD VALUES("BGF685N2","ADHYA","RAMCHANDRA","4TH CROSS SRI NAGAR",24,"2001-01-06","BANGLORE","KARNATAKA");
INSERT INTO PANCARD VALUES("BHT654J9","ARUN","RAHUL","9TH CROSS RR NAGAR",22,"2002-08-01","SAGARA","KARNATAKA");
INSERT INTO PANCARD VALUES("NHY396V4","ADHYA","RAMESH","5TH CROSS SHREE NAGAR",24,"2002-11-26","BANGLORE","KARNATAKA");
INSERT INTO PANCARD VALUES("PKE027B6","ASHOK","RJESH","2ND CROSS RAJAJI NAGAR",22,"2000-11-16","SHIVAMOGGA","KARNATAKA");

SELECT * FROM PANCARD WHERE FULL_NAME = "ADHYA";

SELECT * FROM PANCARD WHERE AGE < 22;

SELECT * FROM PANCARD WHERE AGE > 22;

SELECT * FROM PANCARD WHERE AGE <= 22;

SELECT * FROM PANCARD WHERE AGE >= 23;

SELECT * FROM PANCARD WHERE AGE != 24;

SELECT * FROM PANCARD WHERE FULL_NAME = "ASHOK" OR AGE = 23;

SELECT * FROM PANCARD WHERE FULL_NAME = "ASHOK" AND AGE = 22;

SELECT * FROM PANCARD WHERE NOT AGE = 24;

SELECT * FROM PANCARD WHERE AGE BETWEEN 22 AND 24;

SELECT FATHER_NAME FROM PANCARD WHERE FULL_NAME IN ('ADHYA','ARUN');

SELECT COUNT(*) FROM PANCARD;

SELECT COUNT(*) AS TOTAL FROM PANCARD;
 
SHOW DATABASES;

SELECT USER, HOST FROM mysql.user;

CREATE TABLE AADHAR_DETAILS(
	AADHAR_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(25) NOT NULL,
    FATHER_NAME VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(40) NOT NULL,
    AGE INT NOT NULL,
    DOB DATE NOT NULL,
    CITY VARCHAR(20) NOT NULL
);

DROP TABLE AADHAR_CARD;
DROP TABLE AADHAR_DETAILS;

ALTER TABLE AADHAR_DETAILS ADD COLUMN STATE VARCHAR(20) NOT NULL;

RENAME TABLE AADHAR_DETAILS TO AADHAR_CARD;
SELECT * FROM AADHAR_CARD;

INSERT INTO AADHAR_CARD VALUES("876598764567","ADHYA","RAHUL","2ND CROSS RR NAGAR",20,"2002-01-06","BANGLORE","KARNATAKA");
INSERT INTO AADHAR_CARD VALUES("987656784567","ARADHANA","RAHUL","1ST CROSS RAJAJI NAGAR",23,"2000-10-26","BANGLORE","KARNATAKA");
INSERT INTO AADHAR_CARD VALUES("567845673546","ASHIK","RAJESH","2ND CROSS NEHRU NAGAR",21,"2003-05-06","SHIVAMOGGA","KARNATAKA");
INSERT INTO AADHAR_CARD VALUES("984634526273","ADHYA","RAMCHANDRA","4TH CROSS SRI NAGAR",24,"2001-01-06","BANGLORE","KARNATAKA");
INSERT INTO AADHAR_CARD VALUES("567023490125","ARUN","RAHUL","9TH CROSS RR NAGAR",22,"2002-08-01","SAGARA","KARNATAKA");
INSERT INTO AADHAR_CARD VALUES("956215673456","ADHYA","RAMESH","5TH CROSS SHREE NAGAR",24,"2002-11-26","BANGLORE","KARNATAKA");
INSERT INTO AADHAR_CARD VALUES("915798657456","ASHOK","RJESH","2ND CROSS RAJAJI NAGAR",22,"2000-11-16","SHIVAMOGGA","KARNATAKA");

SELECT * FROM AADHAR_CARD WHERE FULL_NAME = "ADHYA";

SELECT * FROM AADHAR_CARD WHERE AGE < 22;

SELECT * FROM AADHAR_CARD WHERE AGE > 22;

SELECT * FROM AADHAR_CARD WHERE AGE <= 22;

SELECT * FROM AADHAR_CARD WHERE AGE >= 23;

SELECT * FROM AADHAR_CARD WHERE AGE != 24;

SELECT * FROM AADHAR_CARD WHERE FULL_NAME = "ASHOK" OR AGE = 23;

SELECT * FROM AADHAR_CARD WHERE FULL_NAME = "ASHOK" AND AGE = 22;

SELECT * FROM AADHAR_CARD WHERE NOT AGE = 24;

SELECT * FROM AADHAR_CARD WHERE AGE BETWEEN 22 AND 24;

SELECT FATHER_NAME FROM AADHAR_CARD WHERE FULL_NAME IN ('ADHYA','ARUN');

SELECT COUNT(*) FROM AADHAR_CARD;

SELECT COUNT(*) AS TOTAL FROM AADHAR_CARD;

TRUNCATE TABLE AADHAR_CARD;

CREATE TABLE DOCTORS (
    DoctorID VARCHAR(10) not null unique,
    DoctorName VARCHAR(100) not null,
    Specialization VARCHAR(50) not null,
    ContactNumber VARCHAR(15) not null unique,
    Email VARCHAR(100) not null unique,
    ExperienceYears INT not null,
    HospitalAffiliation VARCHAR(100) not null
);

ALTER TABLE DOCTORS ADD COLUMN ConsultantionFee DECIMAL(10, 2) NOT NULL;

RENAME TABLE DOCTORS TO DOCTOR_DETAILS;

INSERT INTO DOCTOR_DETAILS VALUES ('D1', 'Dr. Rajesh Kumar', 'Cardiology', '+91-9876543210', 'rajesh.kumar@hospital.com', 10, 'Apollo Hospital', 500.00);
INSERT INTO DOCTOR_DETAILS VALUES ('D2', 'Dr. Sneha Sharma', 'Orthopedics', '+91-9988776655', 'sneha.sharma@hospital.com', 8, 'Fortis Hospital', 800.00);
INSERT INTO DOCTOR_DETAILS VALUES ('D3', 'Dr. Amit Verma', 'Pediatrics', '+91-9123456789', 'amit.verma@hospital.com', 5, 'Max Healthcare', 400.00);
INSERT INTO DOCTOR_DETAILS VALUES ('D4', 'Dr. Priya Iyer', 'Dermatology', '+91-9654321098', 'priya.iyer@hospital.com', 12, 'Manipal Hospital', 600.00);
INSERT INTO DOCTOR_DETAILS VALUES ('D5', 'Dr. Ravi Mehta', 'General Medicine', '+91-8765432109', 'ravi.mehta@hospital.com', 15, 'Narayana Health', 700.00);
INSERT INTO DOCTOR_DETAILS VALUES ('D6', 'Dr. Neha Singh', 'Gynecology', '+91-9445566778', 'neha.singh@hospital.com', 7, 'BLK Super Speciality', 900.00);
INSERT INTO DOCTOR_DETAILS VALUES ('D7', 'Dr. Vikram Joshi', 'Neurology', '+91-8888776655', 'vikram.joshi@hospital.com', 20, 'Apollo Hospital', 1000.00);

SELECT * FROM DOCTOR_DETAILS WHERE DoctorID = 'D6';

SELECT * FROM DOCTOR_DETAILS WHERE DoctorID < 'D4';

SELECT * FROM DOCTOR_DETAILS WHERE DoctorID > 'D4';

SELECT * FROM DOCTOR_DETAILS WHERE DoctorID <= 'D3';

SELECT * FROM DOCTOR_DETAILS WHERE DoctorID >= 'D3';

SELECT * FROM DOCTOR_DETAILS WHERE DoctorID != 'D4';

SELECT * FROM DOCTOR_DETAILS WHERE DoctorID = 'D3' OR ExperienceYears = 8;

SELECT * FROM DOCTOR_DETAILS WHERE DoctorID = 'D3' AND ExperienceYears = 5;

SELECT * FROM DOCTOR_DETAILS WHERE NOT  ExperienceYears = 5;

SELECT * FROM DOCTOR_DETAILS WHERE ExperienceYears BETWEEN 7 AND 12;

SELECT Specialization FROM DOCTOR_DETAILS WHERE DoctorName IN ('Dr. Priya Iyer','Dr. Neha Singh');

SELECT COUNT(*) FROM DOCTOR_DETAILS;

SELECT COUNT(*) AS TOTAL FROM DOCTOR_DETAILS;
 
SHOW DATABASES;

SELECT USER, HOST FROM mysql.user;