CREATE DATABASE RANDOM_ONE;

USE RANDOM_ONE;

CREATE TABLE LIBRARY_BOOK(
	BOOK_ID INT NOT NULL UNIQUE,
    CUSTOMER_NAME VARCHAR(25) NOT NULL,
	NUMBER_OF_BOOKS INT NOT NULL,
    BORROWED_DATE DATE NOT NULL,
    BOOK_NAME VARCHAR(50) NOT NULL,
    AUTHOR_NAME VARCHAR(60) NOT NULL,
	PAGES INT NOT NULL
);

RENAME TABLE LIBRARY_BOOK TO LIBRARY;

ALTER TABLE LIBRARY ADD COLUMN LAST_DATE_TO_RETURN DATE NOT NULL;

SELECT * FROM LIBRARY;

DROP TABLE LIBRARY;

DROP TABLE lIBRARY_BOOK;

INSERT INTO LIBRARY VALUES(121,"ARUN",1,"2024-08-23","IKIGAI","JAPANESE",340,"2024-10-29");
INSERT INTO LIBRARY VALUES(122,"ASHIK",1,"2024-09-20","DEATH","SADGURU",300,"2024-10-19");
INSERT INTO LIBRARY VALUES(123,"ADHYA",1,"2024-08-12","ATOMIC HABITS","JAMES CLEAR",440,"2024-10-22");
INSERT INTO LIBRARY VALUES(124,"AMITH",2,"2024-08-28","HERE, THERE AND EVERYWHERE","SUDHAMURTHY",390,"2024-10-20");
INSERT INTO LIBRARY VALUES(125,"ARUN",1,"2024-09-17","HYPER FOCUS","JAMES",349,"2024-10-29");
INSERT INTO LIBRARY VALUES(126,"ADHYA",3,"2024-09-20","IKIGAI","JAPANESE",360,"2024-10-26");
INSERT INTO LIBRARY VALUES(127,"ASHIK",1,"2024-08-18","ATOMIC HABITS","JAMES CLEAR",348,"2024-10-27");

SELECT * FROM LIBRARY WHERE CUSTOMER_NAME = "ARUN";

SELECT * FROM LIBRARY WHERE NUMBER_OF_BOOKS < 2;

SELECT * FROM LIBRARY WHERE PAGES > 350;

SELECT * FROM LIBRARY WHERE PAGES <= 350;

SELECT * FROM LIBRARY WHERE LAST_DATE_TO_RETURN >= "2024-10-18";

SELECT * FROM LIBRARY WHERE BOOK_ID != 124;

SELECT * FROM LIBRARY WHERE CUSTOMER_NAME = "ARUN" OR NUMBER_OF_BOOKS = 2;

SELECT * FROM LIBRARY WHERE CUSTOMER_NAME = "ARUN" AND BOOK_NAME = "HYPER FOCUS";

SELECT * FROM LIBRARY WHERE NOT BOOK_NAME = "IKIGAI";

SELECT * FROM LIBRARY WHERE BOOK_ID BETWEEN 122 AND 126;

SELECT CUSTOMER_NAME FROM LIBRARY WHERE BOOK_NAME IN ('HYPER FOCUS','IKIGAI');

SELECT COUNT(*) FROM LIBRARY;

SELECT COUNT(*) AS TOTAL FROM LIBRARY;
 
SHOW DATABASES;

SELECT USER, HOST FROM mysql.user;


CREATE TABLE SHOP_PURCHASE(
	BILL_ID INT NOT NULL UNIQUE,
    CUSTOMER_NAME VARCHAR(25) NOT NULL,
	SECTION VARCHAR(20) NOT NULL,
	SIZE VARCHAR(20) NOT NULL,
    DRESS_TYPE VARCHAR(30) NOT NULL,
	COLORS_AVAILABLE INT NOT NULL,
	AMOUNT INT NOT NULL
);

RENAME TABLE SHOP_PURCHASE TO SHOPPING;

ALTER TABLE SHOPPING ADD COLUMN BILL_NUMBER INT NOT NULL UNIQUE;

SELECT * FROM SHOPPING;

INSERT INTO SHOPPING VALUES(201,"KAVANA","LADIES","XXL","KURTA",3,800,2);
INSERT INTO SHOPPING VALUES(202,"KAVYA","KIDS","L","KURTA",2,890,7);
INSERT INTO SHOPPING VALUES(203,"KEERTHI","LADIES","M","T-SHIRT",5,500,3);
INSERT INTO SHOPPING VALUES(204,"KAVERI","KIDS","XL","T-SHIRT",2,300,4);
INSERT INTO SHOPPING VALUES(205,"KAVANA","LADIES","XL","DRESS MATERIAL",3,1800,5);
INSERT INTO SHOPPING VALUES(206,"KAVYA","LADIES","L","SAREE",6,2800,6);
INSERT INTO SHOPPING VALUES(207,"KAVANA","KIDS","XL","JEANS",4,2890,9);


SELECT * FROM SHOPPING WHERE SECTION = "KIDS";

SELECT * FROM SHOPPING WHERE COLORS_AVAILABLE < 6;

SELECT * FROM SHOPPING WHERE AMOUNT > 900;

SELECT * FROM SHOPPING WHERE AMOUNT <= 1000;

SELECT * FROM SHOPPING WHERE SIZE >= "XL";

SELECT * FROM SHOPPING WHERE SIZE != "XXL";

SELECT * FROM SHOPPING WHERE CUSTOMER_NAME = "KAVYA" OR SIZE = "L";

SELECT * FROM SHOPPING WHERE CUSTOMER_NAME = "KAVYA" AND SIZE = "L";

SELECT * FROM SHOPPING WHERE NOT SIZE = "L";

SELECT * FROM SHOPPING WHERE SIZE BETWEEN "M" AND "XL";

SELECT CUSTOMER_NAME FROM SHOPPING WHERE SIZE IN ('M','L');

SELECT COUNT(*) AS TOTAL FROM SHOPPING;
 
SHOW DATABASES;

SELECT USER, HOST FROM mysql.user;

USE RANDOM_ONE;

CREATE TABLE TOOB_LIGHT(
	ID INT NOT NULL UNIQUE,
    BRAND_NAME VARCHAR(25) NOT NULL,
	VOLTAGE VARCHAR(20) NOT NULL,
	CONSUMPTION VARCHAR(20) NOT NULL,
    COLOR VARCHAR(10) NOT NULL,
    SIZE VARCHAR(20) NOT NULL,
	AMOUNT INT NOT NULL
);

RENAME TABLE TOOB_LIGHT TO TUBE_LIGHT;

ALTER TABLE TUBE_LIGHT ADD COLUMN GST INT NOT NULL;

SELECT * FROM TUBE_LIGHT;

INSERT INTO TUBE_LIGHT VALUES(111,"PILIPS","8VOLTS","5VOLTS","WHITE","340CM",400,250);
INSERT INTO TUBE_LIGHT VALUES(112,"SYSKA","10VOLTS","4VOLTS","WHITE","440CM",800,280);
INSERT INTO TUBE_LIGHT VALUES(113,"EVEREADY","8VOLTS","2VOLTS","WHITE","840CM",1400,189);
INSERT INTO TUBE_LIGHT VALUES(114,"PILIPS","6VOLTS","3VOLTS","WHITE","640CM",500,220);
INSERT INTO TUBE_LIGHT VALUES(115,"EVEREADY","8VOLTS","5VOLTS","WHITE","440CM",1200,160);
INSERT INTO TUBE_LIGHT VALUES(116,"PILIPS","10VOLTS","5VOLTS","WHITE","340CM",1390,150);
INSERT INTO TUBE_LIGHT VALUES(117,"SYSKA","7VOLTS","4VOLTS","WHITE","740CM",480,189);


SELECT * FROM TUBE_LIGHT WHERE BRAND_NAME = "SYSKA";

SELECT * FROM TUBE_LIGHT WHERE GST < 600;

SELECT * FROM TUBE_LIGHT WHERE AMOUNT > 900;

SELECT * FROM TUBE_LIGHT WHERE AMOUNT <= 1000;

SELECT * FROM TUBE_LIGHT WHERE SIZE >= "350CM";

SELECT * FROM TUBE_LIGHT WHERE SIZE != "840CM";

SELECT * FROM TUBE_LIGHT WHERE BRAND_NAME = "SYSKA" OR AMOUNT <= 500;

SELECT * FROM TUBE_LIGHT WHERE BRAND_NAME = "PILIPS" AND SIZE = "340CM";

SELECT * FROM TUBE_LIGHT WHERE NOT SIZE = "340CM";

SELECT * FROM TUBE_LIGHT WHERE SIZE BETWEEN "440CM" AND "740CM";

SELECT BRAND_NAME FROM TUBE_LIGHT WHERE SIZE IN ('340CM','740CM');

SELECT COUNT(*) AS TOTAL FROM TUBE_LIGHT;
 
SHOW DATABASES;

SELECT USER, HOST FROM mysql.user;

TRUNCATE TABLE TUBE_LIGHT; 





